spring:
  application:
    #应用名称
    name: account-service-api
  #jdbc 配置文件内容
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.0.2.126:3306/boathouse?characterEncoding=utf-8
    schema: classpath:db/schema.sql
    data: classpath:db/data.sql
    username: root
    password: yunzhihui123
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    url: jdbc:mysql://10.0.2.126:3306/boathouse?characterEncoding=utf-8
    user: root
    password: yunzhihui123

server:
  #访问端口号
  port: 8081
  tomcat:
    #编码格式
    uri-encoding: utf-8
  servlet:
    #Api路由前缀
    context-path: /api/v1.0